machine:
  services:
    - docker-compose

dependencies:
  post:
    - docker-compose build .
    #- docker build -t $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/steward-ecr:$CIRCLE_SHA1 .

#test:
  #post:
  #  - docker run -d -p 8080:8080 --name sample-go-webapp $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/go-sample-webapp:$CIRCLE_SHA1; sleep 10
  #  - curl --retry 10 --retry-delay 5 localhost:8080 | grep "Hello World!"

deployment:
  prod:
    branch: develop
    commands:
      - ./deploy.sh


